import { randomBytes } from "crypto";
import { readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

/**
 * GitHub raw URL for the production docker-compose.yml.
 * This is the single source of truth for the compose template.
 */
const COMPOSE_RAW_URL =
  "https://raw.githubusercontent.com/DaoFlow-dev/DaoFlow/main/docker-compose.yml";

/**
 * Embedded fallback: read docker-compose.yml from the repo root at build time.
 * Bun's bundler inlines this at `bun build` so it's available offline.
 *
 * We use a try/catch because the file path is relative to the source location
 * and may not resolve in all environments.
 */
let embeddedCompose: string | null = null;
try {
  // Resolve relative to this source file → ../../docker-compose.yml (repo root)
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const composePath = resolve(__dirname, "../../docker-compose.yml");
  embeddedCompose = readFileSync(composePath, "utf-8");
} catch {
  // Will be null if file not found (e.g. running from bundled binary)
}

/**
 * Fetch the production docker-compose.yml.
 *
 * Strategy:
 *   1. Download latest from GitHub raw (ensures updates without CLI rebuild)
 *   2. Fall back to build-time embedded copy (works offline)
 *   3. If both fail, throw with clear error message
 */
export async function fetchComposeYml(): Promise<string> {
  // Try downloading from GitHub first
  try {
    const response = await fetch(COMPOSE_RAW_URL, {
      signal: AbortSignal.timeout(10_000) // 10s timeout
    });
    if (response.ok) {
      const content = await response.text();
      if (content.includes("services:") && content.includes("daoflow")) {
        return content;
      }
    }
  } catch {
    // Network error — fall through to embedded
  }

  // Fall back to embedded copy
  if (embeddedCompose) {
    return embeddedCompose;
  }

  throw new Error(
    "Could not fetch docker-compose.yml from GitHub and no embedded copy available.\n" +
      `Try downloading manually: curl -fsSL ${COMPOSE_RAW_URL} -o docker-compose.yml`
  );
}

/**
 * Generate a cryptographically secure random hex string.
 */
function secureHex(bytes: number): string {
  return randomBytes(bytes).toString("hex");
}

/**
 * Generate the .env file with secure random secrets.
 * Passwords can be provided manually or auto-generated.
 */
export function generateEnvFile(opts: {
  version: string;
  domain: string;
  port: number;
  postgresPassword?: string;
  temporalPostgresPassword?: string;
  authSecret?: string;
  encryptionKey?: string;
}): string {
  const pgPass = opts.postgresPassword ?? secureHex(24);
  const temporalPgPass = opts.temporalPostgresPassword ?? secureHex(24);
  const authSecret = opts.authSecret ?? secureHex(32);
  const encKey = opts.encryptionKey ?? secureHex(16); // 32 hex chars

  const scheme = opts.domain === "localhost" ? "http" : "https";
  const portSuffix =
    (scheme === "https" && opts.port === 443) || (scheme === "http" && opts.port === 80)
      ? ""
      : `:${opts.port}`;

  return `# DaoFlow configuration — generated by daoflow install
# Edit this file to change settings, then run: daoflow upgrade --yes

# ── Version ───────────────────────────────────────────────────
DAOFLOW_VERSION=${opts.version}

# ── Public URL ────────────────────────────────────────────────
BETTER_AUTH_URL=${scheme}://${opts.domain}${portSuffix}
DAOFLOW_PORT=${opts.port}

# ── Database (auto-generated password) ────────────────────────
POSTGRES_PASSWORD=${pgPass}

# ── Temporal Database (auto-generated password) ───────────────
TEMPORAL_POSTGRES_PASSWORD=${temporalPgPass}

# ── Secrets (auto-generated, do not share) ────────────────────
BETTER_AUTH_SECRET=${authSecret}
ENCRYPTION_KEY=${encKey}

# ── Deployment Worker ─────────────────────────────────────────
# DEPLOY_TIMEOUT_MS=600000

# ── Temporal ──────────────────────────────────────────────────
# TEMPORAL_NAMESPACE=daoflow
# TEMPORAL_TASK_QUEUE=daoflow-deployments
# TEMPORAL_UI_PORT=8233

# ── Optional: S3 backup storage ──────────────────────────────
# S3_ENDPOINT=https://s3.amazonaws.com
# S3_BUCKET=daoflow-backups
# S3_ACCESS_KEY=
# S3_SECRET_KEY=
# S3_REGION=us-east-1

# ── Optional: SMTP for email notifications ───────────────────
# SMTP_HOST=
# SMTP_PORT=587
# SMTP_USER=
# SMTP_PASSWORD=
# SMTP_FROM=
`;
}

/**
 * Parse a .env file into a key-value Record.
 */
export function parseEnvFile(content: string): Record<string, string> {
  const env: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    env[key] = value;
  }
  return env;
}

/**
 * Get the default DaoFlow install directory.
 */
export function defaultInstallDir(): string {
  if (process.platform === "darwin") {
    return `${process.env.HOME}/.daoflow/server`;
  }
  return "/opt/daoflow";
}
