import { randomBytes } from "crypto";

/**
 * DaoFlow production docker-compose.yml template.
 * All values come from .env — no hardcoded secrets.
 */
export function generateComposeYml(version: string): string {
  return `# DaoFlow — The agentic platform to host deterministic systems
# Generated by daoflow install v${version}
# All configuration is in .env — edit that file, not this one.

services:
  daoflow:
    image: ghcr.io/daoflow/daoflow:\${DAOFLOW_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "\${PORT:-3000}:3000"
    environment:
      DATABASE_URL: \${DATABASE_URL}
      REDIS_URL: \${REDIS_URL}
      BETTER_AUTH_SECRET: \${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: \${BETTER_AUTH_URL}
      ENCRYPTION_KEY: \${ENCRYPTION_KEY}
      NODE_ENV: production
      PORT: "3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/trpc/healthCheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  db:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: daoflow
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: daoflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U daoflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
`;
}

/**
 * Generate the .env file with secure random secrets.
 */
export function generateEnvFile(opts: {
  version: string;
  domain: string;
  port: number;
  postgresPassword?: string;
  authSecret?: string;
  encryptionKey?: string;
}): string {
  const pgPass = opts.postgresPassword ?? randomBytes(24).toString("hex");
  const authSecret = opts.authSecret ?? randomBytes(32).toString("hex");
  const encKey = opts.encryptionKey ?? randomBytes(16).toString("hex"); // 32 hex chars

  const scheme = opts.domain === "localhost" ? "http" : "https";

  return `# DaoFlow configuration — generated by daoflow install
# Edit this file to change settings, then run: daoflow upgrade --yes

# Version
DAOFLOW_VERSION=${opts.version}

# Public URL
BETTER_AUTH_URL=${scheme}://${opts.domain}
PORT=${opts.port}

# Database
DATABASE_URL=postgresql://daoflow:${pgPass}@db:5432/daoflow
POSTGRES_PASSWORD=${pgPass}

# Redis
REDIS_URL=redis://redis:6379

# Secrets (auto-generated, do not share)
BETTER_AUTH_SECRET=${authSecret}
ENCRYPTION_KEY=${encKey}

# Optional: Private access (uncomment to enable)
# TAILSCALE_AUTHKEY=tskey-auth-xxx
# CF_TUNNEL_TOKEN=eyJ...

# Optional: S3 backup storage
# S3_ENDPOINT=https://s3.amazonaws.com
# S3_BUCKET=daoflow-backups
# S3_ACCESS_KEY=
# S3_SECRET_KEY=
# S3_REGION=us-east-1

# Optional: SMTP for email notifications
# SMTP_HOST=
# SMTP_PORT=587
# SMTP_USER=
# SMTP_PASSWORD=
# SMTP_FROM=
`;
}

/**
 * Parse a .env file into a key-value Record.
 */
export function parseEnvFile(content: string): Record<string, string> {
  const env: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    env[key] = value;
  }
  return env;
}

/**
 * Get the default DaoFlow install directory.
 */
export function defaultInstallDir(): string {
  if (process.platform === "darwin") {
    return `${process.env.HOME}/.daoflow/server`;
  }
  return "/opt/daoflow";
}
